
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Login</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
		.content {
			margin-top: 80px;
		}
	</style>
</head>
<body>

<div class="container content">
	<div class="col-md-12">
        <?php require VIEWS_PATH . 'includes/message.phtml'; ?>
    </div>
	<div class="col-md-4 col-md-offset-4">
		<form action="<?=HOME;?>auth/login" method="POST">
			<div class="form-group">
				<label for="exampleInputEmail1">Email</label>
				<input type="email" class="form-control" placeholder="Email" name="email">
			</div>
			<div class="form-group">
				<label for="exampleInputPassword1">Password</label>
				<input type="password" class="form-control" placeholder="Senha" name="password">
			</div>
			<button type="submit" class="btn btn-default btn-success pull-right">Acessar</button>
		</form>
	</div>
</div>
</body>
</html>
