<?php if(Session\Session::has('success')): ?>
    <div class="alert alert-success">
        <?=Session\Flash::get('success'); ?>
    </div>
<?php endif; ?>


<?php if(Session\Session::has('danger')): ?>
    <div class="alert alert-danger">
        <?=Session\Flash::get('danger'); ?>
    </div>
<?php endif; ?>

<?php if(Session\Session::has('warning')): ?>
    <div class="alert alert-warning">
        <?=Session\Flash::get('warning'); ?>
    </div>
<?php endif; ?>