<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">
	<div class="row">
		<div class="col-12">
			<div class="col-md-4">
				<h1>Suas despesas</h1>
			</div>
			<div class="col-md-2">
				<a href="<?=HOME;?>myexpenses/new" class="btn btn-success">Novo</a>
			</div>
		</div>
		<hr>
	</div>
	<div class="col-md-12">
		<table class="table">
			<thead>
				<tr>
					<th>#</th>
					<th>Descrição</th>
					<th>Valor</th>
					<th>Criado Em</th>
					<th>Ações</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->expenses as $e): ?>
					<tr>
						<td><?=$e['id'];?></td>
						<td><?=$e['description'];?></td>
						<td>R$ <?=number_format($e['value'],2,',','.');?></td>
						<td><?=date('d/m/Y H:i:s', strtotime($e['created_at']));?></td>
						<td>
							<a href="<?=HOME;?>myexpenses/edit/<?=$e['id']?>" class="btn btn-info">Editar</a>
							<a href="<?=HOME;?>myexpenses/remove/<?=$e['id']?>" class="btn btn-danger">Excluir</a>
						</td>
					</tr>
				<?php endforeach;?>
			</tbody>
		</table>
	</div>

</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>