<?php require VIEWS_PATH . 'includes/header.phtml';?>

<div class="container">
    <div class="jumbotron">
        <h2>Lista Produtos </h2>
    </div>
   
    <div class="col-md-12">
            <?php foreach($this->products as $product):?>
                <div class="col-md-4">
                    <img src="http://placehold.jp/350x150.png" class="img-responsive" >
                    <h2><a href="<?=HOME;?>product/<?=$product['id'];?>"><?=$product['name'];?></a></h2>
                    <p><?=$product['description'];?></p>
                    <p>R$ <?=number_format($product['price'],2,',','.');?></p>
                </div>
            <?php endforeach;?>
        </div>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml';?>